```{r}

datos <- read.csv("../Add-noise/dataset_integrado.csv", header = TRUE)
colnames(datos) <- c("Ciudad", "Universidad", "Año", "Genero", "Nivel", "Campo", "Nota", "Carrera", "Region", "Cantidad")
datos$Nota <- as.numeric(datos$Nota)
```

```{r}

head(datos)
```

## Codificación One-Hot Encode

```{r}

# Función para realizar One-Hot Encoding
one_hot_encode <- function(data, variable) {
  # Obtener la matriz codificada
  encoded_matrix <- model.matrix(~ . - 1, data = data[, variable, drop = FALSE])
  
  # Convertir la matriz a un data frame
  encoded_df <- as.data.frame(encoded_matrix)
  
  # Obtener los nombres de las nuevas columnas
  new_column_names <- colnames(encoded_df)
  
  # Eliminar la columna original
  data <- data[, !grepl(variable, colnames(data))]
  
  # Agregar las nuevas columnas al conjunto de datos original
  data <- cbind(data, encoded_df[, -1, drop = FALSE])
  
  # Devolver el conjunto de datos modificado
  return(data)
}
```

## One-Hot sobre el dataset

```{r}

# Uso de la función para codificar "Ciudad"
df_ciudad_encoded <- one_hot_encode(datos, "Ciudad")
head(df_ciudad_encoded)
```

```{r}

# Uso de la función para codificar "Universidad"
df_universidad_encoded <- one_hot_encode(datos, "Universidad")
head(df_universidad_encoded)
```

```{r}

# Uso de la función para codificar "Campo"
df_campo_encoded <- one_hot_encode(datos, "Campo")
head(df_campo_encoded)
```

```{r}

# Uso de la función para codificar "Carrera"
df_carrera_encoded <- one_hot_encode(datos, "Carrera")
head(df_carrera_encoded)
```

## Variables binarias

```{r}

# Función para realizar la codificación binaria
binary_encode <- function(data, variable, category1, category2) {
  # Crear una nueva columna con la codificación binaria
  data[[variable]] <- ifelse(data[[variable]] == category1, 0, 1)
  
  # Devolver el conjunto de datos modificado
  return(data)
}
```

```{r}

# Uso de la función para codificar "Genero"
df_genero <- binary_encode(datos, "Genero", "Hombres", "Mujeres")
head(df_genero)
```

## Codificación binaria sobre el dataset

```{r}

# Uso de la función para codificar "Nivel"
df_nivel <- binary_encode(datos, "Nivel", "PAU", "FP")
head(df_nivel)
```
