```{r}
library(dplyr)
# install.packages("caret")
library(caret)
```

## Cargamos los datos del dataset ya limpio

```{r}
datos <- read.csv("./data/CleanData/dataClean.csv")
```

## 1. Normalización

```{r}
# Seleccionar las columnas numéricas para normalizar
columnas_numericas <- datos[, c("Nota.media", "Número.de.estudiantes")]
```

## Normalizamos las columnas numéricas
```{r}
datos_normalizados <- scale(columnas_numericas)
```

## Agregamos los datos normalizados al conjunto de datos original

```{r}
datos[, c("Nota.media", "Número.de.estudiantes")] <- datos_normalizados
```

## Exportación a CSV

```{r}
# Especifica el nombre del archivo CSV para los datos normalizados
nombre_archivo <- "./data/CleanData/datos_normalizados.csv"

# Guarda los datos normalizados en un nuevo archivo CSV
write.csv(datos, file = nombre_archivo, row.names = FALSE)

# Imprime un mensaje de confirmación
cat("Datos normalizados exportados a", nombre_archivo, "\n")

```

## 2. Escalado

```{r}
# Las columnas a escalar son las mismas que las que se normalizaron
# Seleccionar las columnas numéricas para escalar
columnas_numericas <- datos[, c("Nota.media", "Número.de.estudiantes")]

# Escalar los datos al rango 0-1
escalador <- preProcess(columnas_numericas, method = c("range"))
datos_escalados <- predict(escalador, newdata = columnas_numericas)

# Agregar los datos escalados al conjunto de datos original
datos[, c("Nota.media", "Número.de.estudiantes")] <- datos_escalados
```

## Exportación a CSV

```{r}
# Especifica el nombre del archivo CSV para los datos escalados
nombre_archivo <- "./data/CleanData/datos_escalados.csv"

# Guarda los datos escalados en un nuevo archivo CSV
write.csv(datos, file = nombre_archivo, row.names = FALSE)

# Imprime un mensaje de confirmación
cat("Datos escalados exportados a", nombre_archivo, "\n")
```
